name: pyolp
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pythonocc-core=7.8.1
  - pip
  - pip :
    - git+https://github.com/Tanneguydv/ikpy
    - git+https://github.com/tpaviot/pythonocc-utils
    - python-fcl
    - pyside6
